name: Release

on:
  workflow_dispatch:
    inputs:
      description:
        description: "Release Notes / Description of changes"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Install Dependencies
        run: wally install

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(grep "^version =" wally.toml | cut -d '"' -f 2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Rojo Model
        run: rojo build -o query-builder.rbxm

      - name: Bundle with Darklua
        run: darklua process src/init.luau dist/query-builder.luau

      - name: Zip Source
        run: zip -r src.zip src

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: v${{ env.VERSION }}
          body: ${{ inputs.description }}
          files: |
            query-builder.rbxm
            dist/query-builder.luau
            src.zip
